### ISSUE TITLE
Enhancement request: Add external_id option

### ISSUE THREAD

**Issue by msamblanet** [pbar1/mfaws#7]
Would it be possible to add a CLI argument to allow us to pass an external id to use with assume-role?

**Comment by pbar1** [comment]
Sure! #9

**Comment by pbar1** [comment]
Check out the latest release, [v1.0.5](https://github.com/pbar1/mfaws/releases/tag/1.0.5)

**Comment by msamblanet** [comment]
Thanks @pbar1 - I got pulled onto another project for a bit but will test it out as soon as I get a chance.
